### ISSUE TITLE
workspace switch not working

### ISSUE THREAD

**Issue by mvaldes14** [iberianpig/fusuma-plugin-wmctrl#12]
Just found out about fusuma, overall it works pretty good with some minor issues. 
I run manjaro KDE on my dell xps 13 and somehow the workspace switch setting is not working, i have reversed all of my keybindings back to default so to switch spaces left and right is with keys `super+ctrl+left/right` but somehow the native worksapce 'next/prev` doesnt do anything, im not even seeing those being detected in the output of fusuma.

My desktop setup is a simple 2 column arrangement
0 1

here's my gem list
```
fusuma (2.1.0)
fusuma-plugin-keypress (0.5.0)
fusuma-plugin-wmctrl (1.1.0)
```

i do have `wmctrl` installed and here is my config that i have supplemented with the native commands for now.

```
3:
    left:
      command: 'xdotool key super+ctrl+Left' 
      workspace: 'next' # Switch to next workspace
      keypress:
        LEFTSHIFT: 
          window: 'next' # Move window to next workspace
        LEFTMETA:
          command: 'xdotool key --clearmodifiers super+ctrl+Left' # Move window to left side
    right:
      command: 'xdotool key super+ctrl+Right' 
      workspace: 'prev' # Switch to previous workspace
      keypress:
        LEFTSHIFT: 
          window: 'prev' # Move window to previous workspace
        LEFTMETA:
          command: 'xdotool key --clearmodifiers super+ctrl+Right'  # Move window to right side
    up:
      command: 'xdotool key Control_L+F10' # Workspace overview
      keypress:
        LEFTMETA:
          window:
            maximized: 'toggle' # Toggle Maximize/Unmaximize Window
    down:
      command: 'xdotool key Control_L+F12' #minimise all windows
      keypress:
        LEFTMETA:
          window: 'close' # Close window
```

any pointers on how to get it done with this plugin will be appreciated
