### ISSUE TITLE
"window" properties don't work

### ISSUE THREAD

**Issue by Casper133** [iberianpig/fusuma-plugin-wmctrl#8]
I have 3 different window properties, but none of them work. Workspace property works fine. 

My config:
```yml
swipe:
  3:
    left:
      workspace: 'next'
      keypress:
        LEFTSHIFT: 
          window: 'next'
    right:
      workspace: 'prev'
      keypress:
        LEFTSHIFT: 
          window: 'prev'
    up:
      command: 'xdotool key ctrl+t'
      keypress:
        LEFTSHIFT:
          command: 'xdotool key --clearmodifiers ctrl+shift+t'
    down:
      command: 'xdotool key ctrl+w'
  4:
    left:
      command: 'xdotool key alt+Right'
    right:
      command: 'xdotool key alt+Left'
    up:
      command: 'xdotool key Control_L+F10'
    down:
      command: 'xdotool key Shift_L+Alt_L+Tab'
      keypress:
        LEFTMETA:
          window: 'close'

pinch:
  2:
    in:
      command: 'xdotool keydown ctrl click 4 keyup ctrl'
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl'

plugin: 
  inputs:
    libinput_command_input:
      enable-tap: true
      enable-dwt: true
      show-keycodes: true
```

Gems versions:
```
fusuma (2.0.2)
fusuma-plugin-keypress (0.4.1)
fusuma-plugin-wmctrl (0.4.1)
```
